### ISSUE TITLE
Feature Request: Dark Mode

### ISSUE THREAD

**Issue by adarsh1001** [sakusaku3939/DeepLAndroid#17]
A simple dark/AMOLED black mode that gets triggered via the System theme would be appreciated.

**Comment by Quantenzitrone** [comment]
For example, as a button in the top right corner where clicking changes the theme between light, dark and AMOLED.

**Comment by sakusaku3939** [comment]
Dark mode supported thanks to @S-H-Y-A's contribution. :tada:
You can get the new version here.
https://github.com/sakusaku3939/DeepLAndroid/releases/tag/v4.2

At this time, only Android 10, which comes standard with dark mode switching in the system, supports it.
(I'm currently looking for a way to switch without being affected by design updates on the DeepL server.)
