### ISSUE TITLE
This app does not seem to have been built using R8.

### ISSUE THREAD

**Issue by S-H-Y-A** [sakusaku3939/DeepLAndroid#26]
I think you uploaded debug build apk.

You need to add this code or build the apk with release option if you want to build using R8.

```
android {
    buildTypes {
+        debug {
+            shrinkResources true
+            minifyEnabled true
+            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
+        }
        release {
            shrinkResources true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
```

**Comment by sakusaku3939** [comment]
Sorry for my lack of words. I tried to create a release signature, but it was blocked by play protect because I have never published an app on play store, so I could not install it.

If this change allows me to apply R8 in the debug signature, I would like to incorporate it in the next version.
Thank you.
