### ISSUE TITLE
HTML code visible

### ISSUE THREAD

**Issue by M0lyk** [sakusaku3939/DeepLAndroid#39]
First of all, thank you very much for this application that cannot be rated on F-droid. It's very simple, very practical, and necessary. 
A big thank you!

I point out a small error that you will understand immediately when you see the attached screenshot :

![Screenshot_20210902-060750~2](https://user-images.githubusercontent.com/1733940/131781812-c8059a6d-c98e-40f7-ae3e-2daa5885cb88.png)

Application v5.0,
in light or dark theme,
in the upper or lower language choice :

The title of the column is called "Translate to" (french : traduire en) OR "Original text" followed by an HTML code " & nbsp "

Thank you.

**Comment by sakusaku3939** [comment]
I could not reproduce the problem because my DeepL design version is different, but the language selection is not customized in any way, so it could be a problem on the DeepL server side.
Sorry I couldn't solve your problem!
![Screenshot_20210902-181208](https://user-images.githubusercontent.com/53967490/131818264-05cbc3ec-f273-4cb7-a6bb-a7923af7dd09.png)
![Screenshot_20210902-181216](https://user-images.githubusercontent.com/53967490/131818364-4ff00fe1-1b7e-4ada-b57d-8cf8033aa399.png)
