### ISSUE TITLE
Native app using the DeepL API

### ISSUE THREAD

**Issue by hank-milliken** [sakusaku3939/DeepLAndroid#81]
Hi, thanks you for your work. I was thinking about implementing app similar to yours, but using the DeepL API. 

So I just want to share with you, that it seems possible to achieve that. DeepL API is callable outside of the browser without any hassle. It is the same endpoint that DeepL web uses.

It would be great to implement fast native app, instead of slower webview. But of course this is just suggestion, I just wanted to share this possibility with you.

![image](https://user-images.githubusercontent.com/89867413/166159163-3e2bde94-d978-4da0-baf3-bf0087c4b306.png)

Cheers,
Hank

**Comment by sakusaku3939** [comment]
Hi! Thanks for your suggestion.
However, I have no plans to incorporate that feature into this app in the future.

The reason is that if I adopt the DeepL API, it would have to change the code significantly, which would change the usability.
Also, the free version of the API can only translate up to 500,000 characters per month, so in some cases, users will need to register their own API key.

If you have any other questions, please feel free to reply. 👍
