### ISSUE TITLE
[Feature Request] Automatically delete cookies

### ISSUE THREAD

**Issue by FBIAgent05** [sakusaku3939/DeepLAndroid#93]
Automatically delete cookies when exiting the app

**Comment by sakusaku3939** [comment]
Hi. Continuous development is closed, but this time I made it as part of a security update.
I have added settings to v8.3 because of the number of feature requests. :+1:

https://github.com/sakusaku3939/DeepLAndroid/releases/tag/v8.3

![image](https://github.com/sakusaku3939/DeepLAndroid/assets/53967490/3ae9709c-0012-45de-9384-b371856cc907)
![image](https://github.com/sakusaku3939/DeepLAndroid/assets/53967490/f45c7dcf-5ec2-49d0-a16c-b5527725367b)
