### ISSUE TITLE
Dark Mode no longer respected

### ISSUE THREAD

**Issue by pistolius** [sakusaku3939/DeepLAndroid#99]
Dark theme is no longer working in the app. Potentially due to an Android Update as v8 was working fine until recently.

Phone: Pixel 6 Pro with Android 13

**Comment by sakusaku3939** [comment]
One possibility is that setForceDark has been discontinued in Android 13.
Thanks for reporting this.

**Comment by sakusaku3939** [comment]
I [fixed this](https://github.com/sakusaku3939/DeepLAndroid/commit/b542cbf261b7f9ffa7d053b7f955365ff4e739df) for Android 13, but found that the DeepL site has dark mode disabled due to some property.
(For example, it works for https://translate.google.com/).

It may take a little more time to figure this out.

**Comment by pistolius** [comment]
It is now showing dark mode again? Android 13 fixed, indeed.

**Comment by sakusaku3939** [comment]
It wasn't working when debugging, but now it seems to be working.
I don't know why, but I'm glad it's fixed.🙃

**Comment by guidot** [comment]
Unfortunately it still isn't working here. I am on Android 12.1. When writing in the app I get multiple
`Dark mode cannot be used because ALGORITHMIC_DARKENING is not suppo...` (rest is cut off).

**Comment by sakusaku3939** [comment]
@guidot
Some devices do not have ALGORITHMIC_DARKENING.
However, this seems to be the only way to force dark mode on Android 12 for now...
